# Edit this file with your own plugin name.
# Please also change the LibraryTemplate package and class names. 
name: RedstoneUtilities
main: me.kevinwells.redstoneutilities.RedstoneUtilities
version: 0.84
depend: [RedstoneChips]
